name: upper-build
on:
    push:
        paths:
            - ".github/workflows/upper-build.yml"
            - "upper/**"
    workflow_dispatch: # manual trigger
jobs:
    build:
        name: build-dotnet-upper
        runs-on: ubuntu-latest
        steps:
            - run: go version
            - uses: actions/setup-go@v5
              with:
                go-version: '1.22'
            
            # - name: Checkout code
            #   uses: actions/checkout@4
            # - run: go build
            #   working-directory: ./upper
            # - run: ./upper foo the bar
            #   working-directory: ./upper